---
- ansible.builtin.set_fact:
    is_font_file: "{{  '.ttf' in gnome_font.url or '.otf' in gnome_font.url }}"

# Install a font from a ZIP file
- name: Download and unzip font file for {{ gnome_font.name }}
  ansible.builtin.unarchive:
    src: "{{ gnome_font.url }}"
    dest: "/tmp/"
    remote_src: true
  # Unarchive module support the following extensions: .zip, .tar, .tar.gz, .tar.bz2, .tar.xz, and .tar.zst
  when: not is_font_file
  become: true
  changed_when: false

# Install a font from a .ttf or .otf file
- name: Download font file for {{ gnome_font.name }}
  ansible.builtin.get_url:
    url: "{{ gnome_font.url }}"
    dest: "/tmp/{{ gnome_font.fonts }}"
  when: is_font_file
  become: true
  changed_when: false

- name: Install font {{ gnome_font.name }}
  when: not is_font_file
  block:
    - name: Find font files
      ansible.builtin.find:
        paths: /tmp
        patterns: "{{ gnome_font.fonts }}"
      register: r_gnome_fonts

    - name: Copy fonts
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: /usr/local/share/fonts/
        remote_src: true
        mode: 0774
      become: true
      with_items: "{{ r_gnome_fonts.files }}"

- name: Install font {{ gnome_font.name }}
  ansible.builtin.copy:
    src: "/tmp/{{ gnome_font.fonts }}"
    dest: /usr/local/share/fonts/
    remote_src: true
    mode: 0774
  become: true
  when: is_font_file
